version: 2.1

aliases:
  - &executor $DOCKER_USER/base-executor:latest
  - &docker-version 19.03.13

jobs:
  build-and-push:
    docker:
      - image: *executor
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - setup_remote_docker:
          version: *docker-version
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
          docker build --build-arg GH_TOKEN=${GH_TOKEN} --no-cache -t $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$(echo $CIRCLE_SHA1 | cut -c -7) .
          docker tag $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$(echo $CIRCLE_SHA1 | cut -c -7) $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:latest
          docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME --all-tags
workflows:
  pipeline:
    jobs:
      - build-and-push:
          context:
            - dockerhub-context
            - STAGING
          filters:
            branches:
              only:
                - master
